import type { Metadata } from "next";
import Footer from "@/components/global/footer";
import "@/styles/globals.css";
import Navbar from "@/components/global/navbar";
import GradientBackground from "@/components/shared/GradientBackground";

export const metadata: Metadata = {
  title: "Programmers' Den",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <Navbar />
        <main className="min-h-screen">
          {/* {children} */}
          <GradientBackground className="py-10">{children}</GradientBackground>
        </main>
        <Footer />
      </body>
    </html>
  );
}
