import type { Metadata } from "next";
import "@/styles/globals.css";
import LayoutWrapper from "@/components/global/LayoutWrapper";

export const metadata: Metadata = {
  title: "Programmers' Den",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <LayoutWrapper>{children}</LayoutWrapper>
      </body>
    </html>
  );
}
